# Generated by Django 5.2.8 on 2025-11-24 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_marca_producto_tipo_mascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='productos.categoria'),
        ),
    ]
