# Generated by Django 5.2.8 on 2025-11-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_vip',
            field=models.BooleanField(default=False, help_text='Indica si el usuario tiene estatus VIP (Descuentos, etc.)', verbose_name='Es Cliente VIP'),
        ),
    ]
